name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: fwal/setup-swift@d43a564349d1341cd990cfbd70d94d63b8899475 
      with: 
        swift-version: "5.3.3"
    - name: Get swift version
      run: swift --version # Swift 5.3.3
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
      env:
          DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
    - name: Run tests
      run: swift test -v
      env:
          DEVELOPER_DIR: /Applications/Xcode13.app/Contents/Developer
